version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: ai-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs/:/etc/nginx/certs/:ro
    depends_on:
      - frontend
      - backend
